### ISSUE TITLE
Extend GH Actions.

### ISSUE THREAD

**Issue by JiriPavela** [tfiedor/perun#111]
Our GH Actions configuration currently handles only automated tests and docs compilation. We want to extend the GH Actions pipeline with:

- [x] Pylint checks and mypy analysis. Tox has those runs already configured, but we need to resolve all the errors before we can make it part of our CI/CD pipeline.
  - [x] Mypy
  - [x] Pylint
- [x] Docs deployment to GH pages.
- [ ] Generating changelog. 
- [x] Uploading Perun to PyPI.
- [x] Automated tagging of new versions.

**Comment by tfiedor** [comment]
As we discussed we will solve the generating of changelog, which is not as straightforward for automatization to manual periodical releases (either by me or Jirka).
