### ISSUE TITLE
init issues

### ISSUE THREAD

**Issue by rpodola** [tfiedor/perun#14]
There is some error using just `perun init` command on empty directory (if there is not some vcs yet).
`$>Error: Invalid value for "--vcs-type": invalid choice: pvcs. (choose from git)` Maybe it is wanted behaviour but it seems to me like an error.
Another problem is that the `perun init` (now on directory with some vcs initialized) command requiring root permissions `$>fatal: writing to shared config 'shared.yml' requires root permissions`

**Comment by tfiedor** [comment]
Thanks for notification.

1) Currently only git is supported as a wrapped vcs, so one has to run "perun init --vcs-type=git". pvcs was created as default and was meant as a simple lightweight version control system. But it is not implemented, as it has lowest priority.

2) One of the todo's is moving the shared config somewhere else, where it will not require root permissions. On some system configurations, the perun is installed in folder, which is guarded by root permissions, and so one has to run "sudo perun init --vcs-type=git". This is unwanted feature, that I will hopefully solve before final release.

**Comment by tfiedor** [comment]
Solved in https://github.com/tfiedor/perun/commit/6c2ffe6d13c77a4b0520c54335b9facbafcecab3
