### ISSUE TITLE
[CLI] perun init

### ISSUE THREAD

**Issue by PeterMocary** [tfiedor/perun#210]
The 'perun init' command triggers the following dialog:
- You are not in Perun instance. Do you wish to init empty Perun with git? [y/N]:

I would expect the command to trigger such dialog only when git is not initialized and would also reword it for that purpose.

**Comment by tfiedor** [comment]
This should have been solved in one of the recent releases (please, rebase and confirm it is solved).

**Comment by PeterMocary** [comment]
Oh, my bad. It is fixed. Thanks!
