### ISSUE TITLE
[Perun import] Add support for providing generic Profile Stats file

### ISSUE THREAD

**Issue by JiriPavela** [tfiedor/perun#250]
Perun import and showdiff should support user-provided file that extends the Profile Stats section in the showdiff output.

**Comment by jirka-h** [comment]
I have attached a sample CSV file:

[perun_input.csv](https://github.com/user-attachments/files/16456963/perun_input.csv)

It contains this info:
```
#Stackfile,Exit_code,Result1_name,Result1_value,Result1_unit,Result1_higher_is_better
```

For each result, there are 4 values:
name
value
unit
direction

The name, unit, and direction are always the same. We could keep this information in the column name, like this, using the pipe character (|) to separate the metric name, unit, and "higher is better" information.
```
#Stackfile,Exit_code,Result1|bogo-ops-per-second-real-time|bogo-ops-per-second|higher_is_better
Run1/kill-threadsNO1_perf_record.perf-folded.gz,0,18511.379883
Run2/kill-threadsNO1_perf_record.perf-folded.gz,0,16463.042429
Run3/kill-threadsNO1_perf_record.perf-folded.gz,0,27043.820382
Run4/kill-threadsNO1_perf_record.perf-folded.gz,0,16562.478509
Run5/kill-threadsNO1_perf_record.perf-folded.gz,0,18575.145957
```

Let me know what you think about this proposal. I prefer to compress name, unit, and direction into column names to avoid duplication. The last string (direction) could be 'higher_is_better' and 'lower_is_better'. We can also omit 'Result1|' and have just 'bogo-ops-per-second-real-time|bogo-ops-per-second|higher_is_better'. On second thought, I like this variant the best. 

To validate the file, we can use a simple Pandas script:
```
#!/usr/bin/env python3

import pandas as pd
df = pd.read_csv('perun_input.csv')
print(df.columns)
print(df.loc[:, 'Result1_value'].describe())
```

**Comment by JiriPavela** [comment]
Great, thanks for providing us with an example input. The compacted/compressed CSV format seems nice and easy enough to parse, so I think we can go with that one. If I understand it correctly, in case of multiple profile stats, the specification would simply be in additional columns, e.g.:
```
#Stackfile,Exit_code,stat1|stat1_unit|stat1_direction,stat2|stat2_unit|stat2_direction
Run1/kill-threadsNO1_perf_record.perf-folded.gz,0,18511.379883,956.36
```
Is that correct?

**Comment by jirka-h** [comment]
Thanks for the review! 

Right, for other metrics, we would just add more columns as in your example.
