### ISSUE TITLE
Collection phase 'before' fails, but the resulting exit code is 0 [minor bug]

### ISSUE THREAD

**Issue by JiriPavela** [tfiedor/perun#49]
**Overview**
----------------
There seems to be a small bug with 'before' collection phase producing improper exit code in case of failure. Although it is a minor issue, it causes inconsistency during testing and could cause confusion / errors when perun would be invoked in scripts etc.

**Disclaimer**: the bug reproduction should be attempted only after the #48 PR is merged, as the additional checks for failures are implemented there.

**Example**
---------------
The bug can be reproduced using the following command (while being in the perun directory):

```perun collect -c tests/collect_trace/cpp_sources/tst.cpp trace```

which produces following result:

```
[!] Prerun [DONE] in 0.00s [!]
Loading workload generator specifications ...[DONE]

Collecting profiles for tests/collect_trace/cpp_sources/tst.cpp
 = processing generator 
[100%] Collecting data by trace
Starting the pre-processing phase... [FAILED]
fatal: error while before_collect phase: Supplied binary parameter '/home/jirka/perun/tests/collect_trace/cpp_sources/tst.cpp' is not an executable ELF file.
[!] Collect [DONE] in 0.00s [!]
[!] Batch Job Run [DONE] in 0.04s [!]
[!] Overall Profiling [DONE] in 0.07s [!]
```

However the exit code of this command is 0:

```
~/perun$ echo $?
0
```

which it probably shouldn't, as the function 'before' actually returns exit code 3 in this case.

**Comment by tfiedor** [comment]
Fixed in some PR.
