### ISSUE TITLE
Generated profile is incorrect.

### ISSUE THREAD

**Issue by rpodola** [tfiedor/perun#8]
Section 'units' should be a structure format instead of a list.
Present format:
'units': [
      'memory': 'MB',
      'time': 'ns'
    ]
Desired format:
'units': {
      'memory': 'MB',
      'time': 'ns'
    }
Maybe it would be good to set a default record (e.g. "memory": "B") if not given by collector.

**Comment by tfiedor** [comment]
Default record is good idea. I though the initial issue was with nulls, but I will finally fix this and change your collectors so it will fit.

**Comment by tfiedor** [comment]
Should be closed by 2e3161d2081de7a4bd8273d7554d2227ead51732
