### ISSUE TITLE
Zero value in address records.

### ISSUE THREAD

**Issue by rpodola** [tfiedor/perun#9]
Rarely there are zero values in the address records in profile which seems to be invalid.

**Comment by tfiedor** [comment]
Do you have any idea, why such records appear in profiles? AFAIK, zero addresses should be protected, as this is, where kernel space is.

**Comment by rpodola** [comment]
There are _ptr_ pointer recorded instead of _nptr_ in code bellow (malloc.c)
`
   if(!profiling && ptr != NULL){
      
      ad_log("realloc", size, nptr);

      if(ptr != nptr){
         ad_log("free", 0, ptr);
      }
`

**Comment by tfiedor** [comment]
Closing the issue, as this was fixed by PR #12.
